GET http://localhost:8080/currency/currencies

###
GET http://localhost:8080/currency

###
GET http://localhost:8080/currency/bbb

###
POST http://localhost:8080/currency/save?code=CNY&name=Chinese Yuan&sign=%C2%A5
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080//exchangeRate/exchangeRates

###
GET http://localhost:8080/exchangeRate/CNYAUD


###
GET http://localhost:8080/exchangeRate/exchangeRates

###
POST http://localhost:8080/exchangeRate/exchangeRates?baseCurrencyCode=CNY&targetCurrencyCode=AUD&rate=0.52

###
GET http://localhost:8080/exchangeRate/exchange?from=CNY&to=AUD&amount=1

###
GET http://localhost:8080/exchangeRate/exchange?from=AUD&to=RUB&amount=10

###
PATCH http://localhost:8080/exchangeRate/AUDRUB?rate=10011

###
GET http://localhost:8080/currency/route3
